stages:
- build
- deploy

.job_template: &deploy_job
  stage: deploy

  image: docker:latest

  services:
  - docker:dind

  before_script:
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

  script:
  - docker pull ubuntu:16.04
  - docker build -t konecnyjakub/wesnoth -f $VERSION/Dockerfile .
  - docker tag konecnyjakub/wesnoth konecnyjakub/wesnoth:$VERSION
  - docker push konecnyjakub/wesnoth:$VERSION

  only:
    - master@konecnyjakub/wesnoth-docker

.job_template: &build_job
  stage: build

  image: docker:latest

  services:
  - docker:dind

  script:
  - docker pull ubuntu:16.04
  - docker build -t konecnyjakub/wesnoth -f $VERSION/Dockerfile .

  except:
    - master@konecnyjakub/wesnoth-docker

deploy:wesnoth1.12:
  <<: *deploy_job
  variables:
    VERSION: "1.12"

deploy:wesnoth1.13:
  <<: *deploy_job
  variables:
    VERSION: "1.13"

build:wesnoth1.12:
  <<: *build_job
  variables:
    VERSION: "1.12"

build:wesnoth1.13:
  <<: *build_job
  variables:
    VERSION: "1.13"
