stages:
- deploy

.job_template: &deploy_job
  stage: deploy

  image: docker:latest

  services:
  - docker:dind

  before_script:
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

  script:
  - docker pull ubuntu:16.04
  - docker build -t konecnyjakub/wesnoth -f $VERSION/Dockerfile .
  - docker tag konecnyjakub/wesnoth konecnyjakub/wesnoth:$VERSION
  - docker push konecnyjakub/wesnoth:$VERSION

  only:
    - master@konecnyjakub/wesnoth-docker

wesnoth112:
  <<: *deploy_job
  variables:
    VERSION: "1.12"

wesnoth113:
  <<: *deploy_job
  variables:
    VERSION: "1.13"
