stages:
- build
- deploy

.job_template: &deploy_job
  stage: deploy

  image: docker:latest

  services:
  - docker:dind

  before_script:
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

  script:
  - docker build -t konecnyjakub/wesnoth -f $VERSION/Dockerfile $VERSION
  - docker tag konecnyjakub/wesnoth konecnyjakub/wesnoth:$VERSION
  - docker push konecnyjakub/wesnoth:$VERSION

  only:
    - master@irdyansages/wesnoth-docker

.job_template: &build_job
  stage: build

  image: docker:latest

  services:
  - docker:dind

  script:
  - docker build -t konecnyjakub/wesnoth -f $VERSION/Dockerfile $VERSION

  except:
    - master@irdyansages/wesnoth-docker

deploy:wesnoth1.16:
  <<: *deploy_job
  variables:
    VERSION: "1.16"

deploy:wesnoth1.18:
  <<: *deploy_job
  environment:
    name: dockerhub
    url: https://hub.docker.com/r/konecnyjakub/wesnoth/
  after_script:
  - docker push konecnyjakub/wesnoth:latest
  variables:
    VERSION: "1.18"

build:wesnoth1.16:
  <<: *build_job
  variables:
    VERSION: "1.16"

build:wesnoth1.18:
  <<: *build_job
  variables:
    VERSION: "1.18"
