stages:
- build
- deploy

.job_template: &deploy_job
  stage: deploy

  image: docker:latest

  services:
  - docker:dind

  before_script:
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

  script:
  - docker build -t konecnyjakub/wesnoth -f $VERSION/Dockerfile $VERSION
  - docker tag konecnyjakub/wesnoth konecnyjakub/wesnoth:$VERSION
  - docker push konecnyjakub/wesnoth:$VERSION

  only:
    - master@konecnyjakub/wesnoth-docker

.job_template: &build_job
  stage: build

  image: docker:latest

  services:
  - docker:dind

  script:
  - docker build -t konecnyjakub/wesnoth -f $VERSION/Dockerfile $VERSION

  except:
    - master@konecnyjakub/wesnoth-docker

deploy:wesnoth1.14:
  <<: *deploy_job
  after_script:
  - docker push konecnyjakub/wesnoth:latest
  variables:
    VERSION: "1.14"

build:wesnoth1.14:
  <<: *build_job
  variables:
    VERSION: "1.14"
